# ngrok Kubernetes Operator Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cribl-worker-ingress
  namespace: cribl
spec:
  ingressClassName: ngrok
  rules:
      # Update the URL to match the one provided by ngrok
    - host: ${NGROK_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cribl-worker-logstream-workergroup
                port:
                  number: 10200